events {}

http {
    server {
        listen 80;
        server_name haad.local;
        add_header X-CTF-Flag "HTB{R3c0n_M4st3r_1}";

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /secret-admin-panel/ {
            alias /usr/share/nginx/html/secret-admin-panel/;
            autoindex on;
        }
    }

    server {
        listen 80;
        server_name wordpress.haad.local;
        location / {
            proxy_pass http://172.20.0.3:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;
        server_name joomla.haad.local;
        location / {
            proxy_pass http://172.20.0.5:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;
        server_name drupal.haad.local;
        location / {
            proxy_pass http://172.20.0.7:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;
        server_name tomcat.haad.local;
        location / {
            proxy_pass http://172.20.0.8:8080;
            proxy_set_header Host $host;
        }
    }

    server {
        listen 80;
        server_name jenkins.haad.local;
        location / {
            proxy_pass http://172.20.0.9:8080;
            proxy_set_header Host $host;
        }
    }

    server {
        listen 80;
        server_name splunk.haad.local;
        location / {
            proxy_pass http://172.20.0.10:8000;
            proxy_set_header Host $host;
        }
    }

    server {
        listen 80;
        server_name cgi.haad.local;
        location / {
            proxy_pass http://172.20.0.11:80;
            proxy_set_header Host $host;
        }
    }
}
